# Makefile for the mgetty fax package
#
# SCCS-ID: $Id: Makefile,v 1.15 1993/10/06 00:36:07 gert Exp $ (c) Gert Doering
#
# this is the C compiler to use (on SunOS, the standard "cc" does not
# grok my code, so please use gcc there).
CC=gcc
#CC=cc
#
# For SCO Unix 3.2v4, it may be necessary to define -D__STDC__=0
# If you have problems with dial-in / dial-out on the same line (e.g.
# 'cu' telling you "CAN'T ACCESS DEVICE"), you should try -DBROKEN_SCO_324
#
# On SCO Unix 3.2.2, select(S) refuses to sleep less than a second,
# so use poll(S) instead. Define -DUSE_POLL
#
# Add "-DSVR4" to compile on System V Release 4 unix
#
# For Linux, you don't have to define anything
#
# For SunOS, you don't have to define anything either - but I'm not sure
# if my preliminary port works.
#
# Add "-DISC" to compile on Interactive Unix
#
# Add "-Aa -D_HPUX_SOURCE" to use the Ansi-C-Compiler on HP-UX 8.0x and above
#
# Add "-D_3B1_" to compile on the AT&T 3b1 machine -g.t.
#
# Add "-D_NOSTDLIB_H" if you don't have <stdlib.h>
#
# Add "-DUSE_GETTYDEFS" if you want to use /etc/gettydefs
#
# For machines without the select() call:
#     Add "-DUSE_POLL" if you don't have select, but do have poll
#     Add "-DUSE_READ" if you don't have select or poll
#
# For older SVR systems (with a filename length restriction to 14
#     characters), define -DSHORT_FILENAMES
#
# If you don't have GNU AS, remove "-pipe"!
#
CFLAGS=-Wall -g -O2 -pipe -DUSE_POLL
#CFLAGS=-g -O2 -Wall -pipe
#CFLAGS=-g -O -DSVR4
#CFLAGS=-g -O -DUSE_POLL
#CFLAGS=-Wall -g -O2 -pipe -D_3B1_
# You can remove _NOSTDLIB_H and USE_READ if you have the networking
# library and gcc.
#CFLAGS=-D_3B1_ -D_NOSTDLIB_H -DUSE_READ -DUSE_GETTYDEFS

#
# LDFLAGS specify flags to pass to the linker. You could specify
# additional libraries here, special link flags, ...
#
# For the 3B1, add "-s -shlib"
#
LDFLAGS=
#LDFLAGS=-s -shlib
#
# where the binaries (mgetty + sendfax) live (used for "make install")
#
BINDIR=/usr/local/bin
#
# the fax spool directory
#
FAX_SPOOL=/usr/spool/fax
FAX_SPOOL_IN=$(FAX_SPOOL)/incoming
#
#
# Nothing to change below this line
#
#
OBJS=mgetty.o logfile.o do_chat.o faxrec.o locks.o faxlib.o io.o \
     logname.o utmp.o gettydefs.o

SFAXOBJ=sendfax.o logfile.o locks.o faxlib.o faxrec.o io.o

all:	mgetty sendfax tools/g3cat tools/g3topbm

mgetty: $(OBJS)
	$(CC) -o mgetty $(OBJS) $(LDFLAGS)

sendfax: $(SFAXOBJ)
	$(CC) -o sendfax $(SFAXOBJ) $(LDFLAGS)

tools/g3cat: tools/g3cat.c
	cd tools ; $(CC) $(CFLAGS) -I.. -o g3cat g3cat.c $(LDFLAGS)

tools/g3topbm: tools/g3topbm.c
	cd tools ; $(CC) $(CFLAGS) -I.. -o g3topbm g3topbm.c $(LDFLAGS)

mgetty.info: mgetty.texi
	makeinfo mgetty.texi

# README PROBLEMS
DISTRIB=README.1st mgetty.texi THANKS TODO Makefile ChangeLog policy.h-dist \
        mgetty.c mgetty.h do_chat.c logfile.c logname.c locks.c \
	faxrec.c faxlib.c fax_lib.h sendfax.c io.c utmp.c flow.c gettydefs.c \
	pbmtog3.p1 \
	fax/faxcvt fax/printfax fax/faxspool fax/faxrunq \
	tools/g3cat.c tools/g3topbm.c \
	contrib/README contrib/scrts.c contrib/pbmscale.c contrib/g3toxwd.c \
	contrib/3b1 contrib/faxin.c contrib/Makefile 

policy.h-dist: policy.h
	@rm -f policy.h-dist
	cp policy.h policy.h-dist
	@chmod u+w policy.h-dist

tar:	$(DISTRIB)
	gtar cvfz mgetty014.tpz $(DISTRIB)

shar1:	$(DISTRIB)
	shar -l 40 -o mgetty.sh $(DISTRIB)

shar:	$(DISTRIB)
	shar $(DISTRIB) >mgetty014.sh

policy.h:
	@echo
	@echo "You have to create your local policy.h first."
	@echo "Copy policy.h-dist and edit it."
	@echo
	@exit 1

clean:
	rm *.o

fullclean:
	rm -f *.o mgetty sendfax testgetty tools/g3cat tools/g3topbm

install: mgetty sendfax tools/g3cat
	-mv -f $(BINDIR)/mgetty $(BINDIR)/mgetty.old
	-mv -f $(BINDIR)/sendfax $(BINDIR)/sendfax.old
	cp mgetty sendfax tools/g3cat fax/faxrunq fax/faxspool $(BINDIR)/
	chmod 700 $(BINDIR)/mgetty $(BINDIR)/sendfax
	chmod 700 $(BINDIR)/faxrunq
	chmod 755 $(BINDIR)/faxspool $(BINDIR)/g3cat
	-mkdir $(FAX_SPOOL)
	-mkdir $(FAX_SPOOL_IN)
	-mkdir $(FAX_SPOOL)/outgoing

######## anything below this line was generated by gcc -MM *.c
config.o : config.c mgetty.h config.h 
do_chat.o : do_chat.c mgetty.h 
faxlib.o : faxlib.c mgetty.h fax_lib.h 
faxrec.o : faxrec.c mgetty.h policy.h fax_lib.h 
flow.o : flow.c mgetty.h 
gettydefs.o : gettydefs.c mgetty.h 
io.o : io.c mgetty.h 
locks.o : locks.c mgetty.h policy.h 
logfile.o : logfile.c mgetty.h policy.h 
logname.o : logname.c mgetty.h policy.h 
mgetty.o : mgetty.c mgetty.h policy.h 
sendfax.o : sendfax.c mgetty.h policy.h fax_lib.h 
utmp.o : utmp.c mgetty.h 
