# Makefile for the mgetty fax package
#
# SCCS-ID: $Id: Makefile,v 1.3 1993/09/01 23:00:27 gert Exp $ (c) Gert Doering
#
# this is the C compiler to use (on SunOS, the standard "cc" does not
# grok my code, so please use gcc there).
CC=gcc
#CC=cc
#
# For SCO Unix 3.2.4, it may be necessary to define -D__STDC__=0
# If you have problems with dial-in / dial-out on the same line, you
# should try -DBROKEN_SCO_324
#
# On SCO Unix 3.2.2, select(S) refuses to sleep less than a second,
# so use poll(S) instead. Define -DUSE_POLL
#
# Add "-DSVR4" to compile on System V Release 4 unix
#
# For Linux, you don't have to define anything
#
# For SunOS, you don't have to define anything either - but I'm not sure
# if my preliminary port works.
#
# Add "-DISC" to compile on Interactive Unix
#
# For Systems without the select() call, use poll(), define -DUSE_POLL
#
# If you don't have GNU AS, remove "-pipe"!
#
CFLAGS=-Wall -g -O2 -pipe -DBROKEN_SCO_324 -DUSE_POLL
#CFLAGS=-g -O2 -Wall -pipe
#CFLAGS=-g -O -DSVR4
#CFLAGS=-g -O -DUSE_POLL
#
# where the binaries (mgetty + sendfax) live (used for "make install")
#
BINDIR=/usr/local/bin
#
#
# Nothing to change below this line
#
OBJS=mgetty.o logfile.o do_chat.o faxrec.o locks.o faxlib.o io.o \
     logname.o utmp.o
SFAXOBJ=sendfax.o logfile.o locks.o faxlib.o faxrec.o io.o
all:	mgetty sendfax

mgetty: $(OBJS)
	$(CC) -o mgetty $(OBJS)

sendfax: $(SFAXOBJ)
	$(CC) -o sendfax $(SFAXOBJ)

# README PROBLEMS
DISTRIB=mgetty.texi THANKS Makefile ChangeLog policy.h-dist \
        mgetty.c mgetty.h do_chat.c logfile.c logname.c locks.c \
	faxrec.c faxlib.c fax_lib.h sendfax.c io.c utmp.c \
	pbmtog3.p1 \
	fax/faxcvt fax/printfax fax/faxspool fax/faxrunq \
	contrib/README contrib/scrts.c contrib/pbmscale.c contrib/3b1 \
	contrib/faxin.c contrib/Makefile

policy.h-dist: policy.h
	@rm -f policy.h-dist
	cp policy.h policy.h-dist
	@chmod u+w policy.h-dist

tar:	$(DISTRIB)
	gtar cvfz mgetty014.tpz $(DISTRIB)

shar1:	$(DISTRIB)
	shar -l 40 -o mgetty.sh $(DISTRIB)

shar:	$(DISTRIB)
	shar $(DISTRIB) >mgetty014.sh

policy.h:
	@echo
	@echo "You have to create your local policy.h first."
	@echo "Copy policy.h-dist and edit it."
	@echo
	@exit 1

clean:
	rm *.o

fullclean:
	rm -f *.o mgetty mgetty.work mgetty.busy sendfax

install: mgetty sendfax
	-mv -f $(BINDIR)/mgetty $(BINDIR)/mgetty.old
	-mv -f $(BINDIR)/sendfax $(BINDIR)/sendfax.old
	cp mgetty sendfax fax/faxrunq fax/faxspool $(BINDIR)/
	chmod 700 $(BINDIR)/mgetty $(BINDIR)/sendfax
	chmod 755 $(BINDIR)/faxspool
	chmod 700 $(BINDIR)/faxrunq

######## anything below this line was generated by gcc -MM *.c
do_chat.o : do_chat.c mgetty.h policy.h 
faxlib.o : faxlib.c mgetty.h policy.h fax_lib.h 
faxrec.o : faxrec.c mgetty.h policy.h fax_lib.h 
io.o : io.c mgetty.h policy.h 
locks.o : locks.c mgetty.h policy.h 
logfile.o : logfile.c mgetty.h policy.h 
logname.o : logname.c mgetty.h policy.h 
mgetty.o : mgetty.c mgetty.h policy.h 
sendfax.o : sendfax.c mgetty.h policy.h fax_lib.h 
utmp.o : utmp.c mgetty.h policy.h 
