.TH pvf 1 "14 February 1997"
.IX pvf
.SH NAME
pvf tools \- utilities to convert various sound formats
.sp 0
.SH DESCRIPTION
The \fBpvf tools\fP man page is out of date. Please run the commands from
the new pvf tools with the -h switch for available options.
.SH AUTHOR
Original version from Klaus Weidner.
Copyright (C) 1997 by Marc Eberhard <Marc.Eberhard@Uni-Duesseldorf.DE>
